//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivityTwoWCFAppClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getSum", ReplyAction="http://tempuri.org/IService1/getSumResponse")]
        int getSum(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getSum", ReplyAction="http://tempuri.org/IService1/getSumResponse")]
        System.Threading.Tasks.Task<int> getSumAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getVowels", ReplyAction="http://tempuri.org/IService1/getVowelsResponse")]
        int getVowels(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getVowels", ReplyAction="http://tempuri.org/IService1/getVowelsResponse")]
        System.Threading.Tasks.Task<int> getVowelsAsync(string str);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ActivityTwoWCFAppClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ActivityTwoWCFAppClient.ServiceReference1.IService1>, ActivityTwoWCFAppClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int getSum(int value) {
            return base.Channel.getSum(value);
        }
        
        public System.Threading.Tasks.Task<int> getSumAsync(int value) {
            return base.Channel.getSumAsync(value);
        }
        
        public int getVowels(string str) {
            return base.Channel.getVowels(str);
        }
        
        public System.Threading.Tasks.Task<int> getVowelsAsync(string str) {
            return base.Channel.getVowelsAsync(str);
        }
    }
}
